# Generated by Django 4.0.2 on 2022-02-15 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='fundación',
            new_name='añoFundación',
        ),
    ]
