# Generated by Django 4.0.2 on 2022-02-15 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega1', '0002_rename_fundación_equipo_añofundación'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liga',
            old_name='cnatidadEquipos',
            new_name='cantidadEquipos',
        ),
    ]
